<?php

declare(strict_types=1);

/**
 * Bootstraps the theme and wires together setup, front-end assets, and editor assets.
 */

if (! defined('ABSPATH')) {
    exit;
}

const TLT_VERSION = '0.1.0';

require_once get_theme_file_path('inc/assets.php');
require_once get_theme_file_path('inc/blocks.php');
require_once get_theme_file_path('inc/patterns.php');

foreach (glob(get_theme_file_path('partials/*.php')) ?: [] as $partial_file) {
    require_once $partial_file;
}

/**
 * Registers theme supports and menu locations.
 */
function the_logical_theme_setup(): void
{
    add_theme_support('wp-block-styles');
    add_theme_support('responsive-embeds');
    add_theme_support('editor-styles');
    add_theme_support('automatic-feed-links');
    add_theme_support('post-thumbnails');
    add_editor_style('assets/css/editor.css');

    register_nav_menus([
        'primary' => __('Primary Navigation', 'the-logical-theme'),
        'footer' => __('Footer Navigation', 'the-logical-theme'),
    ]);
}
add_action('after_setup_theme', 'the_logical_theme_setup');

/**
 * Enqueues the front-end asset bundle generated by Vite.
 */
function the_logical_theme_enqueue_assets(): void
{
    the_logical_theme_enqueue_vite_assets();
}
add_action('wp_enqueue_scripts', 'the_logical_theme_enqueue_assets');

/**
 * Loads editor-only styles so the block editor stays aligned with the front end.
 */
function the_logical_theme_enqueue_editor_assets(): void
{
    $editor_css = get_theme_file_uri('assets/css/editor.css');
    $editor_path = get_theme_file_path('assets/css/editor.css');
    $version = file_exists($editor_path) ? (string) filemtime($editor_path) : TLT_VERSION;

    wp_enqueue_style('the-logical-theme-editor', $editor_css, [], $version);
}
add_action('enqueue_block_editor_assets', 'the_logical_theme_enqueue_editor_assets');
