name: Build and Release WordPress Theme

on:
  push:
    branches:
      - master

permissions:
  contents: write  # Concede il permesso di creare una Release

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Creare directory temporanea e copiare i file
        run: mkdir ${{ github.event.repository.name }}-build && rsync -a . ${{ github.event.repository.name }}-build

      - name: Creare il file ZIP del tema
        run: |
          cd ${{ github.event.repository.name }}-build
          zip -r ../${{ github.event.repository.name }}.zip * -x "${{ github.event.repository.name }}-build/*"
          cd ..
      
      - name: Pulizia della directory temporanea
        run: rm -rf ${{ github.event.repository.name }}-build

      - name: Creare una GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: "Release v1.0.${{ github.run_number }}"
          body: "Nuova release del tema WordPress generata automaticamente."
          draft: false
          prerelease: false
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
