name: Build ZIP on Push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Creare directory temporanea per il tema
        run: mkdir -p build/the-logical-theme

      - name: Copiare i file del tema escludendo quelli inutili
        run: rsync -av --exclude='.git' --exclude='.github' --exclude='README.md' --exclude='.gitignore' ./ build/the-logical-theme

      - name: Creare il file ZIP
        run: |
          cd build
          zip -r the-logical-theme.zip the-logical-theme
          mv the-logical-theme.zip ../

      - name: Salvare lo ZIP come Artifact
        uses: actions/upload-artifact@v4
        with:
          name: the-logical-theme
          path: the-logical-theme.zip
